### PR TITLE
Support GNOME 46

### PR DESCRIPTION
**Pull request by ShadowXBoss696**
Changelog:
- Add version 46 to the supported shell version list.
- Bumped the extension version to 10

### CODE REVIEW

**Comment by ShadowXBoss696** [comment]
Hi @fcusr, I recently updated my Linux to GNOME 46 and found that the extension is not working ...
So I manually cloned your repository and updated the following and it worked for me ... Thus raised a PR with the same set of changes ...

Note- I do not know much about GNOME extensions and only raised the PR based on my interests ... So please review it thoroughly and help me understand if any other change is required ... I will follow up on the progress ...

**Comment by teamcons** [comment]
@ShadowXBoss696 the other PR was ignored, and commit history of fcusr isnt super reassuring. I wonder if we would not be better off maintaining this one ourselves

**Comment by ShadowXBoss696** [comment]
@teamcons I have recently gone through several extensions that can be made better with a little more effort. As GNOME being an open-source environment does not consent to upload other sources without consent from the original author, as far as I know about their policies, I decided to rewrite some of these extensions from scratch and hope to keep up with it.

If you have any good ideas regarding it, feel free to discuss about it.

**Comment by Mibea** [comment]
Care to submit the fork as a gnome extention? I can add my themes to your fork. This extention deserves a new chance but i can't pull it off myself.

**Comment by teamcons** [comment]
I could, but leaving this to @ShadowXBoss696, idk if they got an answer yet.
I agree it is better to ask - beside theres no reason to not say it isnt a fork - but i dont like the idea of letting good things rot because their creator is unresponsive, despite GPL license.

**Pull request closed without merging**
